import pandas as pd
train = pd.read_csv('data/final/train_dataset.csv')
test = pd.read_csv('data/final/test_dataset.csv')
print('=== TRAIN ===')
print(f'Shape: {train.shape}')
print(f'Columns: {list(train.columns)}')
print(f'Label dist: {dict(train["label"].value_counts())}')
print(f'Panel dist: {dict(train["panel"].value_counts())}')
print()
print('=== TEST ===')
print(f'Shape: {test.shape}')
print(f'Label dist: {dict(test["label"].value_counts())}')
print(f'Panel dist: {dict(test["panel"].value_counts())}')
print()
print('=== DTYPES ===')
print(train.dtypes)
print()
print('=== SAMPLE ===')
print(train.head(2).to_string())
